### ISSUE TITLE
ValueError: need at most 63 handles, got a sequence of length 66

### ISSUE THREAD

**Issue by morestart** [hengzhe-zhang/EvolutionaryForest#78]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\miniconda3\envs\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\miniconda3\envs\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\miniconda3\envs\lib\multiprocessing\pool.py", line 519, in _handle_workers
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "C:\Users\miniconda3\envs\lib\multiprocessing\pool.py", line 499, in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "C:\Users\miniconda3\envs\lib\multiprocessing\connection.py", line 884, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "C:\Users\miniconda3\envs\lib\multiprocessing\connection.py", line 816, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 66

**Comment by hengzhe-zhang** [comment]
Could you provide a minimal reproducible example? It seems the error is caused by the `multiprocessing` package. I'm not sure whether this error has any relationship with this package.

**Comment by morestart** [comment]
https://github.com/hengzhe-zhang/EvolutionaryForest/blob/master/tutorial/diabetes_regression-CN.md

i use this demo from readme, just change another dataset

**Comment by hengzhe-zhang** [comment]
I'm not sure why you failed. Maybe your dataset is too big? Please try to use a small portion of your data to test whether it still fails.
